services:
  - type: web
    name: seebruecke/frontend
    env: node
    plan: pro
    buildCommand: npm install; npm run build
    pullRequestPreviewsEnabled: true
    region: frankfurt
    repo: https://github.com/seebruecke-org/frontend
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_CMS_DOMAIN
        value: https://cms.seebruecke.org
      - key: NEXT_PUBLIC_GRAPHQL_API
        value: https://api.seebruecke.org/graphql
      - key: NEXT_PUBLIC_IMAGE_HOSTNAME
        value: cms.seebruecke.org
      - key: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
        sync: false
      - key: MATOMO_ENDPOINT
        sync: false
      - key: MATOMO_SITE_ID
        sync: false
      - key: MAILCHIMP_API_KEY
        sync: false
      - key: MAILCHIMP_LIST_ID
        sync: false
      - key: MAILCHIMP_SERVER
        sync: false
    domains:
      - next.seebruecke.org
    disk:
      name: next.js image cache
      mountPath: /opt/render/project/src/.next/cache/images
      sizeGB: 1
