import { Metadata } from "next"
import Layout from "@/components/Layout"

import "@/styles/tailwind.css"
import "@/styles/spende.css"
import "swiper/swiper-bundle.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
}

interface LayoutProps {
  children: React.ReactNode
  pageProps: {
    initialState?: any
    [key: string]: any
  }
}

const RootLayout: React.FC<LayoutProps> = ({ children, pageProps = {} }) => {
  const { initialState = {} } = pageProps
  const { menus } = initialState

  // Uncomment and use this if you need to track route changes
  // useEffect(() => {
  //   const trackRouteChange = (url) => {
  //     fetch(`/api/track?url=${url}`);
  //   };

  //   router.events.on('routeChangeComplete', trackRouteChange);

  //   return () => {
  //     router.events.off('routeChangeComplete', trackRouteChange);
  //   };
  // }, [router.events]);

  return (
    <html lang="en">
      <body>
        <div className="flex flex-col flex-1 min-h-screen">
          <Header
            metaItems={menus?.["header_meta"]?.items}
            items={menus?.["header_main"]?.items}
          />
          <main id="content">{children}</main>
          <Footer
            itemsTakePart={menus?.["footer_take_part"]}
            itemsAbout={menus?.["footer_about"]}
            itemsMeta={menus?.["footer_meta"]}
          />
        </div>
      </body>
    </html>
  )
}

export default RootLayout
