import { Metadata } from "next"
import Layout from "@/components/Layout"

import "@/styles/tailwind.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
